name = "ClaudeBox"
uuid = "a69d1bcb-0a72-4b4d-a563-50e49d53df40"
version = "1.1.0"
authors = ["Claude Assistant"]

[deps]
BinaryBuilder2 = "12aac903-9f7c-5d81-afc2-d9565ea332af"
BinaryBuilderAuditor = "53524979-5234-6e31-4220-6120654b694c"
BinaryBuilderGitUtils = "654d7472-7548-7361-4832-74694762694c"
BinaryBuilderPlatformExtensions = "213f2928-4d72-6f46-7461-4c705f634367"
BinaryBuilderProducts = "21737265-7a69-6e4f-4974-6375646f7270"
BinaryBuilderSources = "316c416d-4527-6863-7465-466137743047"
BinaryBuilderToolchains = "33566f4c-336c-3150-6d30-4374274e6143"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLLGenerator = "73536572-7074-4e69-5270-206c4c6a2061"
JLLPrefixes = "afc68a34-7891-4c5a-9da1-1c62935e7b0d"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KeywordArgumentExtraction = "45533465-3150-2073-4772-41774b207255"
LazyJLLWrappers = "21706172-204c-4d4f-5420-656854206f44"
MultiHashParsing = "73786568-6863-756d-6873-6168796e616d"
OutputCollectors = "6c11c7d4-943b-4e2b-80de-f2cfc2930a8c"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Sandbox = "9307e30f-c43e-9ca7-d17c-c2dc59df670d"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
ScratchSpaceGarbageCollector = "2b218182-314f-4389-a4eb-69d351d2272a"
TreeArchival = "216c6a2e-6c61-7669-6863-726165657274"

[sources.BinaryBuilder2]
rev = "main"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.BinaryBuilderAuditor]
rev = "main"
subdir = "BinaryBuilderAuditor.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.BinaryBuilderGitUtils]
rev = "main"
subdir = "BinaryBuilderGitUtils.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.BinaryBuilderPlatformExtensions]
rev = "main"
subdir = "BinaryBuilderPlatformExtensions.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.BinaryBuilderProducts]
rev = "main"
subdir = "BinaryBuilderProducts.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.BinaryBuilderSources]
rev = "main"
subdir = "BinaryBuilderSources.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.BinaryBuilderToolchains]
rev = "main"
subdir = "BinaryBuilderToolchains.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl.git"

[sources.JLLGenerator]
rev = "main"
subdir = "JLLGenerator.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.KeywordArgumentExtraction]
rev = "main"
subdir = "KeywordArgumentExtraction.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.LazyJLLWrappers]
rev = "main"
subdir = "LazyJLLWrappers.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl.git"

[sources.MultiHashParsing]
rev = "main"
subdir = "MultiHashParsing.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl"

[sources.OutputCollectors]
rev = "master"
url = "https://github.com/JuliaPackaging/OutputCollectors.jl"

[sources.Sandbox]
rev = "main"
url = "https://github.com/JuliaContainerization/Sandbox.jl"

[sources.ScratchSpaceGarbageCollector]
rev = "main"
subdir = "ScratchSpaceGarbageCollector.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl.git"

[sources.TreeArchival]
rev = "main"
subdir = "TreeArchival.jl"
url = "https://github.com/JuliaPackaging/BinaryBuilder2.jl.git"

[compat]
BinaryBuilder2 = "1.0.0"
BinaryBuilderAuditor = "0.2.0"
BinaryBuilderGitUtils = "0.2.0"
BinaryBuilderPlatformExtensions = "0.2.0"
BinaryBuilderProducts = "0.2.0"
BinaryBuilderSources = "0.2.0"
BinaryBuilderToolchains = "0.3.0"
GitHub = "5"
JLLGenerator = "0.4.0"
KeywordArgumentExtraction = "1.1.0"
LazyJLLWrappers = "1.1.0"
MultiHashParsing = "0.2.0"
OutputCollectors = "1.0.0"
REPL = "1.10"
Sandbox = "2.1"
Scratch = "1.2"
ScratchSpaceGarbageCollector = "0.1.1"
TreeArchival = "0.2.0"
julia = "1.11"

[apps.claudebox]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
